name: CD Pipeline
on:
  push:
    branches: [ "main" ]

jobs:
  createimage:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4
  
      - uses: actions/download-artifact@v4
        with:
          path: .

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push the Docker image for gradio app
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/patientsurvival_api:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/patientsurvival_api:latest
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: sudo docker pull $DOCKER_USER/patientsurvival_api:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f patientsurvival_api-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: sudo docker run -it -d -p 80:7860 --name patientsurvival_api-container $DOCKER_USER/patientsurvival_api:latest
